# Generated by Django 4.1.7 on 2023-05-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0008_alter_diagnosticbilldetail_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticbill',
            name='diagnostic_form',
            field=models.BooleanField(choices=[(0, 'ONLINE'), (1, 'OFLINE')], max_length=32),
        ),
    ]
