# Generated by Django 4.1.7 on 2023-05-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0009_alter_diagnosticbill_diagnostic_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holding_amount', models.FloatField(default=0)),
                ('pay_doctor_amount', models.FloatField(default=0)),
                ('profit', models.FloatField(default=0)),
            ],
        ),
    ]
