# Generated by Django 4.1.7 on 2023-05-21 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0010_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='revenue',
            field=models.FloatField(default=0),
        ),
    ]
