# Generated by Django 4.1.7 on 2023-05-21 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0012_transaction_to_user_alter_transaction_base_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='disagnostic_bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Transaction.diagnosticbill'),
        ),
    ]
