# Generated by Django 4.1.7 on 2023-05-21 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0013_transaction_disagnostic_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticbill',
            name='is_pay',
            field=models.BooleanField(default=False),
        ),
    ]
