# Generated by Django 4.1.7 on 2023-05-21 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0014_diagnosticbill_is_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='disagnostic_bill',
        ),
    ]
