# Generated by Django 4.1.7 on 2023-05-21 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Transaction', '0015_remove_transaction_disagnostic_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_from_user', to=settings.AUTH_USER_MODEL)),
                ('disagnostic_bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Transaction.diagnosticbill')),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
