# Generated by Django 4.1.7 on 2023-05-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0017_historypayment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='historypayment',
            name='type',
            field=models.IntegerField(choices=[(0, 'PATIENT_TRANSFER_ADMIN'), (1, 'ADMIN_TRANSFER_PATIENT'), (2, 'ADMIN_TRANSFER_DOCTOR')], default=1),
            preserve_default=False,
        ),
    ]
