# Generated by Django 4.1.7 on 2023-05-21 05:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0018_historypayment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='historypayment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
