# Generated by Django 4.1.7 on 2023-05-21 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0019_historypayment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historypayment',
            old_name='base_user',
            new_name='from_user',
        ),
    ]
