# Generated by Django 4.1.7 on 2023-05-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0020_rename_base_user_historypayment_from_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='historypayment',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
