# Generated by Django 4.1.7 on 2023-05-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0022_diagnosticbilldetail_total_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticbilldetail',
            name='fee_distance_per_one',
            field=models.FloatField(default=0),
        ),
    ]
