# Generated by Django 4.1.7 on 2023-05-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0023_diagnosticbilldetail_fee_distance_per_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='historypayment',
            name='amount_from_user',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='historypayment',
            name='amount_to_user',
            field=models.FloatField(default=0),
        ),
    ]
