export const PRIVATE_ROUTES = {
  patients: '/patients',
  patientById: '/patients-management/:id',
  grantDoctor: '/grant-doctor',
  doctorsManagement: '/doctors-management',
  patientsManagement: '/patients-management',
  departmenstManagement: '/departments-management',
  patientsFinder: '/patients/finder',
  patientsFindered: '/patients/findered',
  patientsFinderDocter: '/patients/finder/docters',
  patientSetting: '/profile',
  doctorSetting: '/profile',
  message: '/patients/messages',
  doctorFinder: '/doctor/finder',
  doctorHistory: '/doctor/history',
  doctorHistoryDetail: '/doctor/history/:id',
  doctorHistoryEdit: '/doctor/history/edit',
  rating: '/rating',
  bookingOnline: '/online/booking',
  bookingOnlineWaiting: '/online/booking/waiting-call',
  bookingOnlineFinderDoctor: '/online/booking/finder-doctor-call',
  patientIntroduceDoctor: '/introduce-doctor',
  doctorProfile: '/introduce-doctor/doctor-profile',
  linkZoom: '/meet/zoom'
};
