# Generated by Django 4.1.7 on 2023-05-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalManagement', '0022_alter_address_address_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.IntegerField(choices=[(1, 'CurrentAddress'), (2, 'BookingCalendarAddress'), (3, 'LivingAdress')], max_length=60, null=True),
        ),
    ]
