# Generated by Django 4.1.7 on 2023-05-17 14:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0024_doctor_diagnostic_fee_doctor_diagnostic_fee_gte_0'),
        ('Booking', '0006_connectdoctor_unique_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectdoctor',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.doctor', unique=True),
        ),
        migrations.AlterField(
            model_name='connectdoctor',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.patient', unique=True),
        ),
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('calender_id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('is_book', models.BooleanField(default=False)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.patient')),
            ],
            options={
                'db_table': 'Calender',
            },
        ),
        migrations.AddConstraint(
            model_name='calender',
            constraint=models.CheckConstraint(check=models.Q(('from_time__lt', models.F('to_time'))), name='check_fromtime_lt_totime'),
        ),
    ]
