# Generated by Django 4.1.7 on 2023-05-19 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0024_doctor_diagnostic_fee_doctor_diagnostic_fee_gte_0'),
        ('Booking', '0007_alter_connectdoctor_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField(default=1)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.patient')),
            ],
            options={
                'db_table': 'Rating',
            },
        ),
    ]
