# Generated by Django 4.1.7 on 2023-05-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0008_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
