# Generated by Django 4.1.7 on 2023-05-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0010_calender_patient_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectdoctor',
            name='distance',
            field=models.FloatField(default=0),
        ),
    ]
