# Generated by Django 4.1.7 on 2023-05-24 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0024_doctor_diagnostic_fee_doctor_diagnostic_fee_gte_0'),
        ('Booking', '0014_connectdoctor_zoom_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalExaminationNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_address', models.TextField(default='')),
                ('patient_phone_number', models.CharField(max_length=12)),
                ('date', models.DateTimeField()),
                ('fee', models.FloatField(default=0)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.patient')),
            ],
        ),
    ]
