# Generated by Django 4.1.7 on 2023-05-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0015_medicalexaminationnotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='calender',
            name='patient_phone_number',
            field=models.CharField(default='', max_length=12),
        ),
    ]
